export const ORG_SWITCHER_CONTENT = `// @generated by s3admin-community-setup — do not edit
"use client"

export function OrgSwitcher(_props: {
  activeOrgSlug: string | null
  collapsed: boolean
  onOrgChange: (slug: string | null) => void
}) {
  return null
}
`
