export const PLAN_ENTITLEMENTS_CONTENT = `\
// @generated by s3admin-community-setup — do not edit
// Community edition — all features unlocked, no plan limits.

export type PlanSource = "subscription" | "default"

export interface PlanEntitlements {
  slug: string
  source: PlanSource
  bucketLimit: number
  fileLimit: number
  thumbnailCache: boolean
  transferTasks: boolean
  recursiveDelete: boolean
  multipleUpload: boolean
  copyFolderToFolder: boolean
  copyBucketToBucket: boolean
  auditLogs: boolean
  searchAllFiles: boolean
  syncTasks: boolean
}

const COMMUNITY_ENTITLEMENTS: PlanEntitlements = {
  slug: "community",
  source: "default",
  bucketLimit: 1000,
  fileLimit: Number.POSITIVE_INFINITY,
  thumbnailCache: true,
  transferTasks: true,
  recursiveDelete: true,
  multipleUpload: true,
  copyFolderToFolder: true,
  copyBucketToBucket: true,
  auditLogs: true,
  searchAllFiles: true,
  syncTasks: true,
}

export async function getUserPlanEntitlements(
  _userId: string,
): Promise<PlanEntitlements | null> {
  return COMMUNITY_ENTITLEMENTS
}
`
