export const SEO_LANDING_PAGES_CONTENT = `\
// @generated by s3admin-community-setup — do not edit
export type SeoLandingCategory = "features" | "providers" | "compare"

type SeoFaqItem = {
  question: string
  answer: string
}

type SeoRelatedLink = {
  href: string
  label: string
}

export type SeoLandingPageConfig = {
  category: SeoLandingCategory
  slug: string
  title: string
  description: string
  h1: string
  intro: string
  problemPoints: string[]
  solutionPoints: string[]
  proofPoints: string[]
  keywords: string[]
  faq: SeoFaqItem[]
  relatedLinks: SeoRelatedLink[]
}

export const seoLandingPages: SeoLandingPageConfig[] = []

export function getSeoLandingPagesByCategory(
  _category: SeoLandingCategory,
): SeoLandingPageConfig[] {
  return []
}

export function getSeoLandingPage(
  _category: SeoLandingCategory,
  _slug: string,
): SeoLandingPageConfig | undefined {
  return undefined
}
`
