export const SEO_CONTENT = `\
// @generated by s3admin-community-setup — do not edit
import type { Metadata } from "next"

export const SITE_NAME = "S3 Admin"
export const DEFAULT_SITE_TITLE =
  "S3 File Manager for AWS, Hetzner & Cloudflare R2"
export const DEFAULT_SITE_DESCRIPTION =
  "Open source S3 file manager with bulk operations, recursive deletes, and cross-provider support for AWS, Hetzner, and Cloudflare R2."
export const DEFAULT_OG_IMAGE_PATH = "/opengraph-image"

export function buildMarketingMetadata(_input: {
  title: string
  description: string
  path: string
}): Metadata {
  return {}
}
`
