export const SERVER_METRICS_CONTENT = `\
// @generated by s3admin-community-setup — do not edit
// Community edition — server metrics collection is a no-op.
export function startServerMetricsCollector() {}
`
