import type { StubEntry } from "./registry.ts"
import fs from "node:fs"
import path from "node:path"

const GENERATED_HEADER = "// @generated by s3admin-community-setup — do not edit\n"

/**
 * Check if a file was generated by either community-setup or cloud setup
 */
export function isGeneratedFile(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return false
  const content = fs.readFileSync(filePath, "utf-8")
  return content.startsWith("// @generated by s3admin")
}

/**
 * Generate fallback content for a stub entry
 */
export function generateStubContent(entry: StubEntry): string | null {
  switch (entry.type) {
    case "skip":
      return null

    case "lib-critical":
      return entry.content

    case "lib-empty":
      return `${GENERATED_HEADER}export {}\n`

    case "page":
      return `${GENERATED_HEADER}import { redirect } from "next/navigation"\nexport default function Page() { redirect("/dashboard") }\n`

    case "layout":
      return `${GENERATED_HEADER}export default function Layout({ children }: { children: React.ReactNode }) {\n  return <>{children}</>\n}\n`

    case "route": {
      const handlers = entry.methods
        .map((m) => `export const ${m} = na`)
        .join("\n")
      return `${GENERATED_HEADER}import { NextResponse } from "next/server"\nconst na = () => NextResponse.json({ error: "Not available in community edition" }, { status: 404 })\n${handlers}\n`
    }
  }
}

/**
 * Write a stub file to disk, creating directories as needed.
 * Only overwrites files that are generated (never user files).
 */
export function writeStubFile(
  projectRoot: string,
  filePath: string,
  content: string,
): boolean {
  const fullPath = path.join(projectRoot, filePath)

  // Never overwrite user files
  if (fs.existsSync(fullPath) && !isGeneratedFile(fullPath)) {
    console.log(`  ⏩ Skipped (user file): ${filePath}`)
    return false
  }

  const dir = path.dirname(fullPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(fullPath, content, "utf-8")
  console.log(`  ✓ Generated: ${filePath}`)
  return true
}
